### PR TITLE
Gatling directory layout and documentation updates

### LINKED ISSUE #4: full example in documentation
Hello, could you please add a full example to the documentation?

at the moment i struggle to define the correct directories:

	:gatling
	Exception in thread "main" java.nio.file.NoSuchFileException: .\target\test-classes
	        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	        at sun.nio.fs.WindowsDirectoryStream.<init>(WindowsDirectoryStream.java:86)
	        at sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(WindowsFileSystemProvider.java:518)
	        at java.nio.file.Files.newDirectoryStream(Files.java:457)
	        at io.gatling.core.util.PathHelper$RichPath$.deepListAux$1(PathHelper.scala:99)
	        at io.gatling.core.util.PathHelper$RichPath$.deepList$extension(PathHelper.scala:105)
	        at io.gatling.core.util.PathHelper$RichPath$.deepFiles$extension(PathHelper.scala)
	        at io.gatling.app.classloader.SimulationClassLoader.simulationClasses(SimulationClassLoader.scala:55)
	        at io.gatling.app.Gatling.loadSimulations(Gatling.scala:92)
	        at io.gatling.app.Gatling.start(Gatling.scala:70)
	        at io.gatling.app.Gatling$.fromArgs(Gatling.scala:59)
	        at io.gatling.app.Gatling$.main(Gatling.scala:44)
	        at io.gatling.app.Gatling.main(Gatling.scala)
	:gatling FAILED

I've defined in my gradle.properties:

	gatling.simulationsDir=gatling/simulations
	gatling.classesDir=gatling/classes

Best regards, Stefan

### LINKED ISSUE #7: Gatling directory layout and documentation updates
As a next step for PR #6 I'm creating this issue to address following.

1. Introduce new boolean parameter `gatlingDirectoryLayout` to `gatling` extension object that will force _old_ directory layout usage
1. Create new tests for `gatlingDirectoryLayout` parameter
1. Adjust plugin `README` to reflect latest plugin changes. As a part of documentation changes I propose to migrate `README` to [`AsciiDoc` format](http://asciidoctor.org/) 

@lkishalmi please provide feedback on my intentions before I start working on them.

### PR DESCRIPTION
**Pull request by eshepelyuk**
Resolves #7 
Resolves #4 

You could check how updated documentation looks like [HERE](https://github.com/eshepelyuk/gradle-gatling-plugin/blob/gatlingLayoutAndDocs/README.adoc)

Additionally tests are improved
* reduce test duration
* more assertions added
* tests are checking `feeders` 
* new scenario for incorrect layout added

@lkishalmi please review

### CODE REVIEW

File: src/main/groovy/com/github/lkishalmi/gradle/gatling/GatlingPlugin.groovy [hunk 1]
```diff
@@ -56,8 +56,9 @@ class GatlingPlugin implements Plugin<Project> {
 
         project.sourceSets {
             gatling {
-                scala.srcDirs 'src/gatling/scala'
-                resources.srcDirs 'src/gatling/resources'
+                scala.srcDirs gatlingExtension.simulationsDir()
```
Comment (lkishalmi) [inline src/main/groovy/com/github/lkishalmi/gradle/gatling/GatlingPlugin.groovy]: Without adding '=' between srcDirs and the arg, the arg is considered as an addition as used below, however the default dir like scala is never inteded to be used.

Comment (eshepelyuk) [inline src/main/groovy/com/github/lkishalmi/gradle/gatling/GatlingPlugin.groovy]: I am not quite sure what change should I implement.

Could you plz provide new piece of code you'd like to be used here ?

File: src/main/groovy/com/github/lkishalmi/gradle/gatling/GatlingExtension.groovy [hunk 2]
```diff
@@ -28,4 +31,27 @@ class GatlingExtension {
...
+    private final boolean isGatlingLayout
+
+    GatlingExtension(Project project) {
+        this.isGatlingLayout = project.file("src/gatling/simulations").exists() && project.file("src/gatling/data").exists() && project.file("src/gatling/bodies").exists()
+    }
+
+    String simulationsDir() {
+        "src/gatling/${ isGatlingLayout ? "simulations" : "scala" }"
+    }
+
```
Comment (lkishalmi) [inline src/main/groovy/com/github/lkishalmi/gradle/gatling/GatlingExtension.groovy]: Why can't dataDir() and bodiesDir() return ```resources/bodies``` and ```resources/data``` respectively and use them in gatlingArgs and in sourceSets.garling.resources.srcDirs as well.

**Comment by lkishalmi** [comment]
Looks good to me, however I'd have some clarifications around the sourcesets.
See my two comments inline.

I've tested this with my NetBeans Gradle plugin which warns on non-existent source root dirs.

**Comment by lkishalmi** [comment]
Something like this:
https://github.com/lkishalmi/gradle-gatling-plugin/commit/8e7118537ef6f9c9480c1dba226fafa0e31d9acf

However it fails one test.

**Comment by eshepelyuk** [comment]
Hello @lkishalmi 

Added 2 commits to PR with 

* bugfix for Windows to properly detect simulations
* tried to apply your suggestions about PR

Please review

File: src/main/groovy/com/github/lkishalmi/gradle/gatling/GatlingPlugin.groovy [hunk 3]
```diff
@@ -83,7 +82,8 @@ class GatlingPlugin implements Plugin<Project> {
                     args "-m"
                     args "-bf", "${project.sourceSets.gatling.output.classesDir}"
                     args "-s", simu
-                    args gatlingExt.gatlingArgs(project)
+                    args "-df", "${project.sourceSets.gatling.output.resourcesDir}"
```
Comment (lkishalmi) [inline src/main/groovy/com/github/lkishalmi/gradle/gatling/GatlingPlugin.groovy]: I'm just asking, that is it a good idea to use the processed resource folder output here where these resources are poured together regardless from their origin?

1. I see the point that this is the processed resources folder.
2. I do not see why don't we use the separate the data and the bodies source directories.
  (I'm not a big Gatling guy, I do not know why they separate these dirs, but if they are having reasons for that, we need to follow that as well)

Comment (eshepelyuk) [inline src/main/groovy/com/github/lkishalmi/gradle/gatling/GatlingPlugin.groovy]: Hello @lkishalmi 

During my work on the plugin and reading `Gatling` documentation I haven't seen any _technical_ reason for keeping bodies and feeders folders separately when invoking `Gatling` tool.

I assume this is a logical separation for the sake of better readability and project structure. From this point of view - we're still keeping it because bodies and feeders are located in different source folders, they are separate for customer and only mixed together in runtime, invisible for customer.

Moreover, I'm more inclined to use `resources` output folder instead of `resources` source folder because of 
* it is common way for many of `Gradle` plugins to take their data
* it is useful for cases when customer wants to preprocess or auto-generate feeder / bodies data by build script

So, I suggest for now to proceed with current approach, unless we receive customer feedback with complaints related to bodies/feeder data location.

**Comment by eshepelyuk** [comment]
@lkishalmi added a reply on your latest comment about PR.

**Comment by lkishalmi** [comment]
Thank you for your recent comment on the resources output dir usage. It sounds reasonable enough.

Also I wish to say thank you for your contribution!

**Comment by eshepelyuk** [comment]
Thank you very much for accepting my work.
Could you please reveal your plans about releasing new plugin version ?

**Comment by lkishalmi** [comment]
Well you might already noticed that v0.2.0 is out.

I've seen your issue #10 on the list, but that can come later in the 0.2.x
series.

Once again, thank you for your contribution!
2016. márc. 29. de. 10:52 ezt írta ("Evgeny Shepelyuk" <
notifications@github.com>):

**Comment by eshepelyuk** [comment]
Yeah, already used new release for my project.
Thank you !
